# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalparks', '0011_auto_20170504_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtripsite',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
